import { useGLTF } from '@react-three/drei'
import { Mesh } from 'three'
import { ModelProps } from '../../types'

export function Plate(props: ModelProps) {
    const { nodes, materials } = useGLTF('/models/scale/plate00.glb')
    return (
        <group {...props} dispose={null}>
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial215 as Mesh).geometry} material={materials['Material.007']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial218 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial219 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial220 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial221 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial222 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial223 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial224 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial225 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial226 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial227 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial228 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial229 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial230 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial231 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial232 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial233 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial234 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial235 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial236 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial237 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial238 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial239 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial240 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial241 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial242 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial243 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial244 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial245 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial246 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial247 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial248 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial249 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial250 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial251 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial252 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial253 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial255 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial256 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial257 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial258 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial259 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial260 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial261 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial262 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial263 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial264 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial265 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial266 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial267 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial268 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial269 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial270 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial271 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial272 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial273 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial274 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial275 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial276 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial277 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial278 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial279 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial280 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial281 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial282 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial283 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial284 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial285 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial286 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial287 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial288 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial289 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial290 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial291 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial292 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial293 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial294 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial295 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial296 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial297 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial298 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial299 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial300 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial301 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial302 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial303 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial304 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial305 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial306 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial307 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial308 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial309 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial310 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial311 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial312 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial313 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial314 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial315 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial316 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial317 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial318 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial319 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial320 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial321 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial322 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial323 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial324 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial325 as Mesh).geometry} material={materials['aiStandardSurface2SG.003']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial326 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial327 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial328 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial329 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial330 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial331 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial332 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial333 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial334 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial335 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial336 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial337 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial338 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial339 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial340 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial341 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial342 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial343 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial344 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial345 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial346 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial347 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial348 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial349 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial350 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial351 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial352 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial353 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial354 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial355 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial356 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial357 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial358 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial360 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial361 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial362 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial363 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial364 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial365 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial366 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial367 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial368 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial369 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial370 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial371 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial372 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial373 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial374 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial375 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial376 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial377 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial378 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial379 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial380 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial381 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial382 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial383 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial384 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial385 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial386 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial387 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial388 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial389 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial390 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial391 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial392 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial393 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial394 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial395 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial396 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial397 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial398 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial399 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial400 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial401 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial402 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial403 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial404 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial405 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial406 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial407 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial408 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial409 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial410 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial411 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial412 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial413 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial414 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial415 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial416 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial417 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial418 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial419 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial420 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial421 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial422 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial423 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial424 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial425 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial426 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial427 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial428 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
            <mesh castShadow receiveShadow geometry={(nodes.defaultMaterial429 as Mesh).geometry} material={materials['aiStandardSurface2SG.002']} position={[0.686, -0.548, 0]} />
        </group>
    )
}

useGLTF.preload('/models/scale/plate00.glb')
